# Generated by Django 4.1.6 on 2023-02-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilestatus",
            options={"verbose_name_plural": "statuses"},
        ),
    ]
