# Generated by Django 4.1.6 on 2023-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profilestatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Male"), (2, "Female")], null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="customers/profiles/avatars/"
            ),
        ),
    ]
